micronaut:
  application:
    name: url-shortener
cassandra:
  default:
    maxSchemaAgreementWaitSeconds: 100
    ssl: true
    basic:
      session-keyspace: "url_shortener"
      contact-points:
        - "127.0.0.1:9042"
      load-balancing-policy:
        local-datacenter: "datacenter1"
#redirect:
#  domain: "http://baby.ul/"

redis:
  uri: redis://localhost
  ssl: true
  timeout: 30s
  caches:
    urls:
      #expire one hour after write
      expire-after-write: 1h

keygenerator:
  api:
    url: "http://localhost:8082"