version: '3.7'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./cassandra_data:/var/lib/cassandra

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./cassandra.cql:/cassandra.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /cassandra.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  redis_container:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Expose native binary CQL port for your apps
    volumes:
      - ./redis_data:/DATA

  key-generator:
    container_name: key-generator
    build:
      context: ../key-generator
      dockerfile: ../key-generator/Dockerfile
    ports:
      - '8082:8082'
    links:
      - cassandra
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra:9042
    depends_on:
      - cassandra

  url-shortener:
    container_name: url-shortener
    build:
      context: ../url-shortener
      dockerfile: ../url-shortener/Dockerfile
    ports:
      - '8080:8080'
    links:
      - cassandra
      - key-generator
      - redis_container
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra:9042
      - REDIS_URI=redis://redis_container
      - KEYGENERATOR_API=http://key-generator:8082
      - ALLOWED_ORIGINS=https://baby-ui-punitpatel214.cloud.okteto.net/
    depends_on:
      - cassandra

  baby-ui:
    container_name: baby-ui
    build:
      context: ../baby-ui
      dockerfile: ../baby-ui/Dockerfile
    ports:
      - '3000:80'
    links:
      - url-shortener
    environment:
      - BABY_API=http://url-shortener:8080
