apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-container
  labels:
    app: redis-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-container
  template:
    metadata:
      labels:
        app: redis-container
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: redis-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: redis-container
  labels:
    app: redis-container
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app: redis-container