apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: punitpatel/url-shortener:dev
          ports:
            - containerPort: 8080
          env:
            - name: CASSANDRA_CONTACT_POINTS
              value: cassandra:9042
            - name: REDIS_URI
              value: redis://redis-container
            - name: KEYGENERATOR_API
              value: http://key-generator:443
            - name: ALLOWED_ORIGINS
              value: https://baby-ui-punitpatel214.cloud.okteto.net
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer
  selector:
    app: url-shortener
  ports:
    - port: 443
      targetPort: 8080