micronaut:
  application:
    name: key-generator
  server:
    port: 8081
cassandra:
  default:
    maxSchemaAgreementWaitSeconds: 100
    ssl: true
    basic:
      session-keyspace: "key_generator"
      contact-points:
        - "127.0.0.1:8080"
      load-balancing-policy:
        local-datacenter: "datacenter1"

test:
  property: nik
---
cache:
  maxSize: 50
  minSize: 20

---
