micronaut:
  application:
    name: key-generator
  server:
    port: 8082

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    cassandra:
      enabled: true

cassandra:
  default:
    maxSchemaAgreementWaitSeconds: 100
    ssl: true
    basic:
      session-keyspace: "key_generator"
      contact-points:
        - ${CASSANDRA_CONTACT_POINTS:`127.0.0.1:9042`}
      load-balancing-policy:
        local-datacenter: "datacenter1"
---
cache:
  maxSize: 50
  minSize: 20

---
